version: '3'

services:
  db:
    image: mysql:5.7
    command: [
        'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - '3307:3307'
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server --port 6380
    ports:
      - '6380:6380'
    expose:
      - '6380'
  web:
    build: .
    command: sh -c 'python manage.py migrate && pytest && python manage.py runserver 0.0.0.0:8040 --noreload'
    volumes:
      - .:/cinema
      - .:/media/
    ports:
      - "8040:8040"
    depends_on:
      - 'db'
      - 'redis'
  celery:
    build: .
    environment:
      - C_FORCE_ROOT=true
    command: celery worker -A cinema -l INFO
    volumes:
      - .:/cinema
    links:
      - redis
    depends_on:
      - 'web'
      - 'redis'