version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_USER: artemiy
      MYSQL_PASSWORD: fisk1
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1fisk
  web:
    build: .
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/cinema
    ports:
      - "8000:8003"
    depends_on:
      - 'db'