# Generated by Django 3.2 on 2021-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('User', 'Пользователь'), ('Admin', 'Администратор'), ('', 'Director')], default='User', max_length=50, verbose_name='Тип юзера'),
        ),
    ]
