# Generated by Django 3.2 on 2021-05-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_moviesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieSubscriptionSerializer',
        ),
    ]
