# Generated by Django 3.2 on 2021-05-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_moviesubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount',
        ),
    ]
