# Generated by Django 3.2 on 2021-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название фильма')),
                ('release_date', models.DateField(null=True)),
                ('duration', models.DurationField(null=True)),
            ],
        ),
    ]
