# Generated by Django 3.2 on 2021-05-03 12:39

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Кино', 'verbose_name_plural': 'Кино'},
        ),
        migrations.CreateModel(
            name='MoviePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=movies.models.get_images_upload_path)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='movies.movie')),
            ],
        ),
    ]
