# Generated by Django 3.2 on 2021-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
