# Generated by Django 3.2 on 2021-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210503_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание фильма'),
        ),
    ]
