# Generated by Django 3.2 on 2021-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_country'),
        ('movies', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(related_name='movies', to='directory.Country'),
        ),
    ]
