# Generated by Django 3.2 on 2021-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviephoto',
            name='is_title',
            field=models.BooleanField(null=True, unique=True),
        ),
    ]
