# Generated by Django 3.2 on 2021-05-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_moviedirectorphoto_is_title'),
        ('movies', '0005_moviephoto_is_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='directory.MovieGenre'),
        ),
    ]
