# Generated by Django 3.2 on 2021-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210506_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierating',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
