# Generated by Django 3.2 on 2021-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_usermovierating_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovierating',
            old_name='score',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
