# Generated by Django 3.2 on 2021-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210506_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
