# Generated by Django 3.2 on 2021-05-08 10:19

import admin_async_upload.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieVideoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_360p', admin_async_upload.models.AsyncFileField(upload_to='')),
                ('video_480p', admin_async_upload.models.AsyncFileField(upload_to='')),
                ('video_720p', admin_async_upload.models.AsyncFileField(upload_to='')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies.movie')),
            ],
        ),
    ]
