# Generated by Django 3.2 on 2021-05-08 10:20

import admin_async_upload.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movievideofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movievideofiles',
            name='video_360p',
            field=admin_async_upload.models.AsyncFileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movievideofiles',
            name='video_480p',
            field=admin_async_upload.models.AsyncFileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movievideofiles',
            name='video_720p',
            field=admin_async_upload.models.AsyncFileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
