# Generated by Django 3.2 on 2021-05-09 12:50

import admin_async_upload.models
from django.db import migrations
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20210509_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movievideofiles',
            name='video_360p',
            field=admin_async_upload.models.AsyncFileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movievideofiles',
            name='video_480p',
            field=admin_async_upload.models.AsyncFileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movievideofiles',
            name='video_720p',
            field=admin_async_upload.models.AsyncFileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
