# Generated by Django 3.2 on 2021-05-14 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0018_auto_20210509_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('movie', models.ManyToManyField(related_name='users_subscribed', to='movies.Movie')),
                ('users', models.ManyToManyField(related_name='movies_subscribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
