# Generated by Django 3.2 on 2021-05-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_moviesubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesubscription',
            old_name='users',
            new_name='user',
        ),
    ]
