# Generated by Django 3.2 on 2021-05-14 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0020_rename_users_moviesubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesubscription',
            name='movie',
            field=models.ManyToManyField(related_name='subscriptions', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='moviesubscription',
            name='user',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
