# Generated by Django 3.2 on 2021-05-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20210514_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesubscription',
            old_name='movie',
            new_name='movies',
        ),
        migrations.RenameField(
            model_name='moviesubscription',
            old_name='user',
            new_name='users',
        ),
    ]
