# Generated by Django 3.2 on 2021-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20210514_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesubscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
