# Generated by Django 3.2 on 2021-05-16 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20210514_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesubscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.CreateModel(
            name='MovieToUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_end', models.DateTimeField(null=True)),
                ('subscription',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_users',
                                   to='movies.moviesubscription')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
