# Generated by Django 3.2 on 2021-05-29 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0023_alter_moviesubscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieToUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_end', models.DateTimeField(null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_users', to='movies.moviesubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='moviesubscription',
            name='users',
            field=models.ManyToManyField(related_name='subscriptions', through='movies.MovieToUserSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
