# Generated by Django 3.2 on 2021-05-29 09:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0024_movietousersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietousersubscription',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moviesubscription',
            name='users',
            field=models.ManyToManyField(related_name='subscriptions', through='movies.MovieToUserSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
