# Generated by Django 3.2 on 2021-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20210529_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietousersubscription',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
