# Generated by Django 3.2 on 2021-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актёр', 'verbose_name_plural': 'Актёры'},
        ),
        migrations.AlterModelOptions(
            name='actormovie',
            options={'verbose_name': 'Актёр в кино', 'verbose_name_plural': 'Актёры в кино'},
        ),
        migrations.AlterModelOptions(
            name='moviedirector',
            options={'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'verbose_name': 'Жанр кино', 'verbose_name_plural': 'Жанры кино'},
        ),
    ]
