# Generated by Django 3.2 on 2021-05-04 12:56

from django.db import migrations

from directory.tasks import get_countries


def get_countries_list(apps, schema_editor):
    get_countries()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20210504_1147'),
    ]

    operations = [
        migrations.RunPython(
            get_countries_list
        )
    ]
