# Generated by Django 3.2 on 2021-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20210504_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorphoto',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
    ]
