# Generated by Django 3.2 on 2021-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_actorphoto_is_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorphoto',
            name='is_title',
            field=models.BooleanField(null=True, unique=True),
        ),
    ]
