# Generated by Django 3.2 on 2021-05-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20210508_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='directory.country'),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_directors', to='directory.country'),
        ),
    ]
