# Generated by Django 3.2 on 2021-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20210529_1313'),
        ('directory', '0012_auto_20210531_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedirector',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='directors', to='movies.Movie'),
        ),
    ]
